const ACTIONS = Object.freeze({
  LOADING_SEARCH_MOVIE: "LOADING_SEARCH_MOVIE",
  SEARCH_MOVIE_LOADED: "SEARCH_MOVIE_LOADED",

  LOADING_MORE_UPCOMING_MOVIE: "LOADING_MORE_UPCOMING_MOVIE",
  MORE_UPCOMING_MOVIE_LOADED: "MORE_UPCOMING_MOVIE_LOADED",

  ERROR: "ERROR",

  LOADING_SINGLE_MOVIE: "LOADING_SINGLE_MOVIE",
  SINGLE_MOVIE_LOADED: "SINGLE_MOVIE_LOADED",

  REDIRECT_TO_HOME: "REDIRECT_TO_HOME",
});

export { ACTIONS };
